### PR TITLE
the obvious: add /.idea/

### PR DESCRIPTION
**Pull request by benzkji**
get up and runing ;-)

### CODE REVIEW

**Comment by matthiask** [comment]
Hmm, why? I don't know what `.idea` even is :-)

(Any reason why you cannot add local/custom ignores to `.git/info/exclude`?)

**Comment by benzkji** [comment]
it's the pycharm project settings folder...

**Comment by benzkji** [comment]
I can easily setup a global core.excludesFile...learnt another thing...up to you to close or merge...

**Comment by matthiask** [comment]
Thanks again. I'm going to reject this. People should set set up their own ignore files for their editors.

**Pull request closed without merging**
